# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='auto_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='challenge',
            name='solution_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='answer',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='solution',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='challengeattempt',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='correct_answers',
            field=models.ManyToManyField(to='challenge.Answer'),
        ),
    ]
