# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20170901_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeattempt',
            name='date',
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
